title: Title
subtitle: Subtitle
author: Mig Reyes
description: Description.

auto: true
source: .
exclude: .gitignore, .sass-cache, _drafts, _site, public, Gemfile, Gemfile.lock, Rakefile, README.md

permalink: /:categories/:title
markdown: rdiscount
pygments: true